accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accounts.views import register_view, UserDetailView, UserUpdateView, UserChangePasswordView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', register_view, name='register'),
    path('<int:pk>/', UserDetailView.as_view(), name='user-detail'),
    path('profile/', UserUpdateView.as_view(), name='user-update-profile'),
    path('change-password/', UserChangePasswordView.as_view(), name='user-change-password'),
]

article/urls.py
from django.urls import path

from article.views import (
    IndexView,
    ArticleView,
    CreateArticleView,
    ArticleUpdateView,
    ArticleCommentCreate,
    ArticleDeleteView,
    UnlikeforArticle,
    LikeforArticle,
    UnlikeforComment,
    LikeforComment
)

app_name = 'article'

urlpatterns = [
    path('', IndexView.as_view(), name='list'),
    path('add/', CreateArticleView.as_view(), name='add'),
    path('<int:pk>/', ArticleView.as_view(), name='view'),
    path('<int:pk>/update', ArticleUpdateView.as_view(), name='update'),
    path('<int:pk>/delete', ArticleDeleteView.as_view(), name='delete'),
    path('<int:pk>/comments/add/', ArticleCommentCreate.as_view(), name='comment-create'),
    path('<int:pk>/likearticle/', LikeforArticle.as_view(), name='like_article'),
    path('<int:pk>/unlikearticle/', UnlikeforArticle.as_view(), name='unlike_article'),
    path('<int:pk>/likecomment/', LikeforComment.as_view(), name='like_comment'),
    path('<int:pk>/unlikecomment/', UnlikeforComment.as_view(), name='unlike_comment')
]

hello/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings


HOMEPAGE_URL = 'articles/'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('article.urls')),
    path('accounts/', include('accounts.urls')),
    path('api_v1/', include('api_v1.urls')),
    path('api_v2/', include('api_v2.urls')),
    path('index/', include('webapp.urls')),
    path('', RedirectView.as_view(url=HOMEPAGE_URL, permanent=True)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.core.validators import MinLengthValidator
from django.conf import settings


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Article(BaseModel):
    title = models.CharField(
        max_length=120,
        null=False,
        blank=False,
        verbose_name='Заголовок',
        validators=(MinLengthValidator(5),)
    )
    content = models.TextField(max_length=3000, null=False, blank=False, verbose_name='Контент')
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.SET_NULL,
        null=True,
        related_name='articles'
    )
    tags = models.ManyToManyField(
        'article.Tag',
        related_name='articles',
        db_table='article_tags'
    )

    class Meta:
        db_table = 'articles'
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'
        permissions = [
            ('сan_have_piece_of_pizza', 'Может съесть кусочек пиццы')
        ]

    def __str__(self):
        return f'{self.id}. {self.author}: {self.title}'



class Comment(BaseModel):
    article = models.ForeignKey(
        'article.Article',
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Статья',
        null=False,
        blank=False
    )
    comment = models.CharField(max_length=200, verbose_name='Комментарий', null=False, blank=False)
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.SET_NULL,
        null=True,
        related_name='comments'
    )

    class Meta:
        db_table = 'comments'
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'
    
    def __str__(self):
        return f'{self.author}: {self.comment}'


class ArticleLike(models.Model):
    author = models.ForeignKey(get_user_model(), on_delete=models.PROTECT)
    article = models.ForeignKey('article.Article', related_name="Likes", on_delete=models.PROTECT)

class CommentLike(models.Model):
    author = models.ForeignKey(get_user_model(), on_delete=models.PROTECT)
    comment = models.ForeignKey('article.Comment', related_name='Commentlikes', on_delete=models.PROTECT)

class Tag(BaseModel):
    tag = models.CharField(max_length=200, verbose_name='Тэг')

    class Meta:
        db_table = 'tags'
        verbose_name = 'Тэг'
        verbose_name_plural = 'Тэги'
    
    def __str__(self):
        return self.tag

article/forms.py
from django import forms

from article.models import Article, Comment


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ('title', 'content', 'tags')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment',)


class SearchForm(forms.Form):
    search_value = forms.CharField(max_length=100, required=False, label='Найти')

api_v2/views/articles.py
from django.shortcuts import get_object_or_404
from rest_framework.response import Response
from rest_framework.views import APIView

from article.models import Article
from api_v2.serializers import ArticleSerializer, article


class ArticleView(APIView):
    def get(self, request, *args, **kwargs):
        articles = Article.objects.all()
        response_data = ArticleSerializer(articles, many=True).data

        return Response(data=response_data)

    def post(self, request, *args, **kwargs):
        article_data = request.data
        serializer = ArticleSerializer(data=article_data)
        serializer.is_valid(raise_exception=True)
        article = serializer.save()
        return Response({'id': article.pk})


class Operation(APIView):
    def get(self, request, pk, *args, **kwargs):
        context = {}
        article = Article.objects.filter(pk=pk)
        serializer = ArticleSerializer(article, many=True).data
        context['data_article'] = serializer
        return Response(context, status=200)

    def put(self, request, pk, *args, **kwargs):
        article_upd = get_object_or_404(Article, pk=pk)
        serializer = ArticleSerializer(article_upd, data=request.data)
        serializer.is_valid(raise_exception=True)
        article_s = serializer.save()
        return Response({'id': article_s.pk})

    def delete(self, request, pk, *args, **kwargs):
        article_del = get_object_or_404(Article, pk=pk)
        print(article_del)
        article_del.delete()
        return Response(status=200)

article/views/articles.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import redirect
from django.views.generic import (
    ListView,
    CreateView,
    DetailView,
    UpdateView,
    DeleteView
)
from django.urls import reverse, reverse_lazy
from django.db.models import Q
from django.utils.http import urlencode

from article.models import Article, ArticleLike, CommentLike
from article.forms import ArticleForm, SearchForm


class IndexView(ListView):
    """
    Представление для просмотра списка статей. Представление реализовано с
    использованием generic-представления ListView.

    В представлении активирована пагинация и реализован поиск
    """
    template_name = 'articles/index.html'
    model = Article
    context_object_name = 'articles'
    ordering = ('title', '-created_at')
    paginate_by = 5
    paginate_orphans = 1

    def get(self, request, **kwargs):
        self.form = SearchForm(request.GET)
        self.search_data = self.get_search_data()
        return super(IndexView, self).get(request, **kwargs)
    
    def get_queryset(self):
        queryset = super().get_queryset()

        if self.search_data:
            queryset = queryset.filter(
                Q(title__icontains=self.search_data) |
                Q(author__icontains=self.search_data) |
                Q(content__icontains=self.search_data)
            )
        return queryset

    def get_search_data(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search_value']
        return None
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search_form'] = self.form
        user = self.request.user
        i = []
        for i in ArticleLike.objects.filter(id=self.kwargs.get('id')):
            i.append(i.article.id)
        context['like_id'] = i
        liked_articles = []
        if self.request.user.is_authenticated:
            ddd = ArticleLike.objects.filter(author=self.request.user)
            for d in ddd:
                liked_articles.append(d.article.pk)
        context['liked_articles'] = liked_articles
        if self.search_data:
            context['query'] = urlencode({'search_value': self.search_data})

        return context


class ArticleView(DetailView):
    model = Article
    template_name = 'articles/view.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        i = []
        for i in CommentLike.objects.filter(id=self.kwargs.get('id')):
            i.append(i.article.id)
        context['comentlike_id'] = i
        liked_comments = []
        if self.request.user.is_authenticated:
            users = CommentLike.objects.filter(author=self.request.user)
            for us in users:
                liked_comments.append(us.comment.pk)
        context['liked_comments'] = liked_comments
        return context

class CreateArticleView(PermissionRequiredMixin, CreateView):
    template_name = 'articles/create.html'
    form_class = ArticleForm
    model = Article
    success_url = reverse_lazy('article:list')
    permission_required = 'article.add_article'

    def form_valid(self, form):
        tags = form.cleaned_data.pop('tags')

        article = form.save(commit=False)
        article.author = self.request.user
        article.save()

        article.tags.set(tags)
        return redirect(self.get_success_url())


class ArticleUpdateView(PermissionRequiredMixin, UpdateView):
    form_class = ArticleForm
    model = Article
    template_name = 'articles/update.html'
    context_object_name = 'article'
    permission_required = 'article.change_article'

    def has_permission(self):
        return self.get_object().author == self.request.user or super().has_permission()

    def get_success_url(self):
        return reverse('article:view', kwargs={'pk': self.kwargs.get('pk')})


class ArticleDeleteView(PermissionRequiredMixin, DeleteView):
    model = Article
    template_name = 'articles/delete.html'
    context_object_name = 'article'
    success_url = reverse_lazy('article:list')
    permission_required = 'article.delete_article'

article/views/comments.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic import CreateView
from django.shortcuts import reverse, get_object_or_404

from article.forms import CommentForm
from article.models import Comment, Article


class ArticleCommentCreate(PermissionRequiredMixin, CreateView):
    template_name = 'comments/create.html'
    form_class = CommentForm
    model = Comment
    permission_required = 'article.add_comment'

    def get_success_url(self):
        return reverse(
            'article:view',
            kwargs={'pk': self.kwargs.get('pk')}
        )
    
    def form_valid(self, form):
        article = get_object_or_404(Article, id=self.kwargs.get('pk'))

        comment = form.instance
        comment.article = article
        comment.author = self.request.user

        return super().form_valid(form)

article/views/likes.py
from django.http import HttpResponseForbidden, HttpResponse
from django.shortcuts import get_object_or_404
from django.views.generic import View
from article.models import ArticleLike, Article, Comment, CommentLike


class LikeforArticle(View):
    def get(self, request, *args, **kwargs):
        article = get_object_or_404(Article, pk=self.kwargs.get('pk'))
        user = request.user
        try:
            ArticleLike.objects.get(article=article, author=user)
            return HttpResponseForbidden('Вы уже поставили лайк)')
        except ArticleLike.DoesNotExist:
            ArticleLike.objects.create(article=article, author=user)
            return HttpResponse(article.Likes.count())


class UnlikeforArticle(View):
    def get(self, request, *args, **kwargs):
        article = get_object_or_404(Article, pk=self.kwargs.get('pk'))
        user = request.user
        try:
            unlike = ArticleLike.objects.get(article=article, author=user)
            unlike.delete()
            return HttpResponse(article.Likes.count())
        except ArticleLike.DoesNotExist:
            return HttpResponseForbidden('Вы еще не лайкнули)')


class LikeforComment(View):
    def get(self, request, *args, **kwargs):
        comment = get_object_or_404(Comment, pk=self.kwargs.get('pk'))
        user = request.user
        try:
            CommentLike.objects.get(comment=comment, author=user)
            return HttpResponseForbidden('Вы уже поставили лайк)')
        except CommentLike.DoesNotExist:
            CommentLike.objects.create(comment=comment, author=user)
            return HttpResponse(comment.Commentlikes.count())


class UnlikeforComment(View):
    def get(self, request, *args, **kwargs):
        comment = get_object_or_404(Comment, pk=self.kwargs.get('pk'))
        user = request.user
        try:
            unlike = CommentLike.objects.get(comment=comment, author=user)
            unlike.delete()
            return HttpResponse(comment.Commentlikes.count())
        except CommentLike.DoesNotExist:
            return HttpResponseForbidden('Вы еще не лайкнули)')

article/templates/partial/article_list.html
{% if is_paginated %}
    {% include 'partial/paginate.html' %}
{% endif %}


{% for article in articles %}
    <div class="box">
        <h3><a href="{% url "article:view" article.pk %}">{{ article.title }}</a></h3>
        <p>
            <label for="selected_articles-{{ article.pk }}">Select:</label>

            <input type="checkbox" name="selected_articles"

                   id="selected_articles-{{ article.pk }}" value="{{ article.pk }}">
        </p>

        <p>
            <a href="{% url 'accounts:user-detail' article.author_id %}">{{ article.author }}</a>
            | {{ article.created_at|date:"d.m.Y H:i:s" }}
        </p>
        {% if user.is_authenticated %}
            {% if article.pk not in liked_articles %}
                <button id="like" data-id="result{{ article.pk }}" onclick="onClick(event)" data-url="{% url 'article:like_article' article.pk %}"><i class="fas fa-thumbs-up" style="font-size: 20px"></i></button>
            {% else %}
                <button id="unlike" data-id="result{{ article.pk }}" onclick="onClickUnlice(event)" data-url="{% url 'article:unlike_article' article.pk %}"><i class="fas fa-thumbs-down" style="font-size: 20px"></i></button>
            {% endif %}
        {% endif %}
        <p id="result{{ article.pk }}">{{ article.Likes.count }}</p>
    </div>

{% empty %}
    <h2 class="text-center">Нет статей</h2>
{% endfor %}


{% if is_paginated %}
     {% include 'partial/pagination.html' %}
{% endif %}
<script src="https://kit.fontawesome.com/bf48221072.js" crossorigin="anonymous"></script>

article/templates/partial/form.html
{% if not fields_only %}
    {% csrf_token %}
{% endif %}

{% for error in form.non_field_errors %}
   <p class="form-error">{{ error }}</p>
{% endfor %}

{% for field in form %}
   <p><label for="{{ field.id_for_label }}">{{ field.label }}</label></p>
   {% for error in field.errors %}
       <p class="form-error">{{ error }}</p>
   {% endfor %}
   <p {% if field.errors %} class="form-field-error"{% endif %}>{{ field }}</p>
    <br>
{% endfor %}

{% if not fields_only %}
    <p><input type="submit" value="{{ button_text }}"></p>
{% endif %}

article/templates/partial/paginate.html
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?{% if query %}{{ query }}&{% endif %}page=1">&laquo; В начало</a>
            <a href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.previous_page_number }}">Назад</a>
        {% else %}
            <span class="page-disabled">&laquo; В начало</span>
            <span class="page-disabled">Назад</span>
        {% endif %}
        <form class="current-page" method="get">
            <label for="page">
                {% if search_value %}<input type="hidden" name="search" value="{{ search_value }}">{% endif %}
                Страница <input type="text" name="page" id="page" value="{{ page_obj.number }}">
                из {{ page_obj.paginator.num_pages }}.
            </label>
        </form>
        {% if page_obj.has_next %}
            <a href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.next_page_number }}">Далее</a>
            <a href="?{% if query %}{{ query }}&{% endif %}page={{ paginator.num_pages }}">В конец &raquo;</a>
        {% else %}
            <span class="page-disabled">Далее</span>
            <span class="page-disabled">В конец &raquo;</span>
        {% endif %}
    </span>
</div>

article/templates/partial/search_form.html
<form class="text-center" action="" method="GET">
    <label for="{{ search_form.search_value.id_for_label }}">{{ search_form.search_value.label }}:</label>
    {{ search_form.search_value }}
    <input type="submit" value="Search">
    {% for error in search_form.search_value.errors %}
        <p class="form-error">{{ error }}</p>
    {% endfor %}
</form>