api_v1/urls.py
from django.urls import path

from api_v1.views import api_add, get_token_view, subtract_api, multiply_api, divide_api

app_name = 'api_v1'

urlpatterns = [
    path('add/', api_add, name='add_api'),
    path('subtract/', subtract_api, name='subtract_api'),
    path('multiply/', multiply_api, name='multiply_api'),
    path('divide/', divide_api, name='divide_api'),
    path('get_token/', get_token_view, name='get_token'),
]

hello/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings


HOMEPAGE_URL = 'articles/'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('article.urls')),
    path('accounts/', include('accounts.urls')),
    path('api_v1/', include('api_v1.urls')),
    path('api_v2/', include('api_v2.urls')),
    path('index/', include('webapp.urls')),
    path('', RedirectView.as_view(url=HOMEPAGE_URL, permanent=True)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/urls.py
from django.urls import path
from webapp.views import index


app_name = 'web'

urlpatterns = [
    path('', index, name='index'),
]

webapp/views.py
from django.shortcuts import render

# Create your views here.

def index(request, *args, **kwargs):
    return render(request, 'index.html')

webapp/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<input id="A" type="">
<input id="B" type="">
<button onclick="onClick(event)" data-url="{% url 'api_v1:add_api' %}">add</button>
<button onclick="onClick(event)" data-url="{% url 'api_v1:subtract_api' %}">subtract</button>
<button onclick="onClick(event)" data-url="{% url 'api_v1:multiply_api' %}">multiply</button>
<button onclick="onClick(event)" data-url="{% url 'api_v1:divide_api' %}">divide</button>
<p id="result"></p>
<script src="{% static 'js/index.js' %}"></script>
</body>
</html>